//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.ItemCostings = new HashSet<ItemCosting>();
            this.ItemMatCostings = new HashSet<ItemMatCosting>();
            this.ItemPricings = new HashSet<ItemPricing>();
            this.OptionRetails = new HashSet<OptionRetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PrinterName { get; set; }
        public string PrinterPort { get; set; }
        public string PrinterDriver { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string ManagerId { get; set; }
        public bool Active { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string LabelPrinter { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ItemCosting> ItemCostings { get; set; }
        public virtual ICollection<ItemMatCosting> ItemMatCostings { get; set; }
        public virtual ICollection<ItemPricing> ItemPricings { get; set; }
        public virtual ICollection<OptionRetail> OptionRetails { get; set; }
    }
}
