//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckDetail
    {
        public int Id { get; set; }
        public int CheckID { get; set; }
        public int OrderID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Order Order { get; set; }
    }
}
