//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public EmailType()
        {
            this.EmailTemplates = new HashSet<EmailTemplate>();
            this.MeasureEmails = new HashSet<MeasureEmail>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }
        public virtual ICollection<MeasureEmail> MeasureEmails { get; set; }
    }
}
