//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemCostings = new HashSet<ItemCosting>();
            this.ItemMatCostings = new HashSet<ItemMatCosting>();
            this.ItemPricings = new HashSet<ItemPricing>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string WorkOrderDescription { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public bool ApplyToMinimun { get; set; }
        public bool PrintOnWorkOrder { get; set; }
        public bool Active { get; set; }
        public bool ApplyToMinimumWO { get; set; }
        public bool Size { get; set; }
        public bool JobSize { get; set; }
    
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ICollection<ItemCosting> ItemCostings { get; set; }
        public virtual ICollection<ItemMatCosting> ItemMatCostings { get; set; }
        public virtual ICollection<ItemPricing> ItemPricings { get; set; }
    }
}
