//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobType
    {
        public JobType()
        {
            this.Programs = new HashSet<Program>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public bool AlwaysSkipInitialCall { get; set; }
    
        public virtual ICollection<Program> Programs { get; set; }
    }
}
