//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        public Measure()
        {
            this.MeasureEmails = new HashSet<MeasureEmail>();
            this.MeasureMaterials = new HashSet<MeasureMaterial>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Enterred { get; set; }
        public int StoreId { get; set; }
        public string EnterredById { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<MeasureEmail> MeasureEmails { get; set; }
        public virtual ICollection<MeasureMaterial> MeasureMaterials { get; set; }
    }
}
