//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeasureEntities : DbContext
    {
        public MeasureEntities()
            : base("name=MeasureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EmailType> EmailTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<MaterialType> MaterialTypes { get; set; }
        public virtual DbSet<Measure> Measures { get; set; }
        public virtual DbSet<MeasureEmail> MeasureEmails { get; set; }
        public virtual DbSet<MeasureMaterial> MeasureMaterials { get; set; }
        public virtual DbSet<MeasureRoom> MeasureRooms { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<SlotType> SlotTypes { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreType> StoreTypes { get; set; }
        public virtual DbSet<Tech> Teches { get; set; }
        public virtual DbSet<TechCapacity> TechCapacities { get; set; }
        public virtual DbSet<Width> Widths { get; set; }
        public virtual DbSet<StoreWithBranch> StoreWithBranches { get; set; }
    }
}
