//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.OptionRetails = new HashSet<OptionRetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> PrintOnInvoice { get; set; }
        public Nullable<bool> PrintOnWO { get; set; }
        public Nullable<bool> ApplyToMinimum { get; set; }
        public Nullable<bool> ApplyToMinimumWO { get; set; }
        public Nullable<bool> Size { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ICollection<OptionRetail> OptionRetails { get; set; }
        public virtual Program Program { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
