//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ChargeBacks = new HashSet<ChargeBack>();
            this.CheckDetails = new HashSet<CheckDetail>();
            this.AssociatedOrders = new HashSet<Order>();
            this.OrderCustoms = new HashSet<OrderCustom>();
            this.OrderNotes = new HashSet<OrderNote>();
            this.OrderOptions = new HashSet<OrderOption>();
            this.POPhotos = new HashSet<POPhoto>();
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ProgramId { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> JobStatusId { get; set; }
        public Nullable<int> PrimaryOrderId { get; set; }
        public string AssignedToId { get; set; }
        public string CreatedByID { get; set; }
        public string SalesPersonId { get; set; }
        public string EnteredById { get; set; }
        public string ReviewedById { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> BilledDate { get; set; }
        public string PONumber { get; set; }
        public string OriginalPO { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public Nullable<System.DateTime> DrawingDate { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<System.DateTime> Entered { get; set; }
        public string SpecialInstructions { get; set; }
        public string InternalNotes { get; set; }
        public bool Scheduled { get; set; }
        public bool Billed { get; set; }
        public bool Paid { get; set; }
        public bool Called { get; set; }
        public bool CustomerToCall { get; set; }
        public bool Invoice { get; set; }
        public bool NoMinimum { get; set; }
        public bool ScheduledAM { get; set; }
        public bool Cancelled { get; set; }
        public bool Warrenty { get; set; }
        public bool SevenDay { get; set; }
        public decimal CostAmount { get; set; }
        public decimal BilledAmount { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal TripCharge { get; set; }
        public decimal RetailAmount { get; set; }
        public string DrawingNumber { get; set; }
        public int EntryMethodId { get; set; }
        public string FollowUpAction { get; set; }
        public Nullable<int> ServiceLineNo { get; set; }
        public string SPNNotes { get; set; }
        public int XMLOrderCostAmount { get; set; }
        public bool Deleted { get; set; }
        public bool Reviewed { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string CorrelationID { get; set; }
        public string KeyRecNumber { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<System.DateTime> KeyRecDate { get; set; }
        public Nullable<System.DateTime> SvcCompleteSentDate { get; set; }
        public Nullable<System.DateTime> ScheduleEndDate { get; set; }
        public bool Estimate { get; set; }
        public string NUMBER { get; set; }
        public Nullable<int> MarkDown { get; set; }
        public Nullable<decimal> JobSize { get; set; }
    
        public virtual ICollection<ChargeBack> ChargeBacks { get; set; }
        public virtual ICollection<CheckDetail> CheckDetails { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee AssignedTo { get; set; }
        public virtual Employee EnteredBy { get; set; }
        public virtual Employee ReviewedBy { get; set; }
        public virtual Employee SalesPerson { get; set; }
        public virtual EntryMethod EntryMethod { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        public virtual ICollection<Order> AssociatedOrders { get; set; }
        public virtual Order PrimaryOrder { get; set; }
        public virtual Program Program { get; set; }
        public virtual ICollection<OrderCustom> OrderCustoms { get; set; }
        public virtual ICollection<OrderNote> OrderNotes { get; set; }
        public virtual ICollection<OrderOption> OrderOptions { get; set; }
        public virtual ICollection<POPhoto> POPhotos { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}
