//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Options = new HashSet<Option>();
            this.Orders = new HashSet<Order>();
            this.ItemCostings = new HashSet<ItemCosting>();
            this.ItemMatCostings = new HashSet<ItemMatCosting>();
            this.ItemPricings = new HashSet<ItemPricing>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StoreTypeID { get; set; }
        public Nullable<decimal> MinimumPrice { get; set; }
        public Nullable<decimal> MinimumCost { get; set; }
        public Nullable<decimal> MinimumRetail { get; set; }
        public Nullable<double> CustomMultiplier { get; set; }
        public Nullable<double> TripChargeMultiplier { get; set; }
        public Nullable<double> CostMultiplier { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<bool> OnlyBasicToMinimum { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<bool> Active { get; set; }
        public bool Furnish { get; set; }
        public string SKU { get; set; }
        public string SKUDesc { get; set; }
        public string HDType { get; set; }
        public string Name { get; set; }
        public bool InsuranceReplacement { get; set; }
        public bool AllowMaterialStatusUpdate { get; set; }
        public Nullable<int> JobTypeId { get; set; }
        public bool WoodWaiver { get; set; }
        public bool CustomCostByRetail { get; set; }
        public Nullable<int> MarkDown { get; set; }
        public Nullable<int> MarkDownMin { get; set; }
        public Nullable<int> MarkDownMax { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual ICollection<Option> Options { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual StoreType StoreType { get; set; }
        public virtual ICollection<ItemCosting> ItemCostings { get; set; }
        public virtual ICollection<ItemMatCosting> ItemMatCostings { get; set; }
        public virtual ICollection<ItemPricing> ItemPricings { get; set; }
    }
}
