//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    
    [Flags]
    public enum Status : int
    {
        Completed = 2,
        Scheduled = 1,
        Paid = 4,
        Billed = 8,
        Cancelled = 16,
        Sold = 32,
        Calculated = 64
    }
}
