//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Divisor { get; set; }
        public Nullable<int> NumberOfDecimals { get; set; }
        public string LongDescription { get; set; }
        public string LongDescriptionSOSI { get; set; }
    }
}
