//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Width
    {
        public Width()
        {
            this.MeasureMaterials = new HashSet<MeasureMaterial>();
            this.MeasureMaterials1 = new HashSet<MeasureMaterial>();
        }
    
        public int Id { get; set; }
        public double Value { get; set; }
    
        public virtual ICollection<MeasureMaterial> MeasureMaterials { get; set; }
        public virtual ICollection<MeasureMaterial> MeasureMaterials1 { get; set; }
    }
}
