//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.ItemCostings = new HashSet<ItemCosting>();
            this.Programs = new HashSet<Program>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> VendorID { get; set; }
        public int DivisionGroupId { get; set; }
        public bool PrintStatusReport { get; set; }
        public bool MarkBilledWhenPaid { get; set; }
        public bool Active { get; set; }
    
        public virtual DivisionGroup DivisionGroup { get; set; }
        public virtual ICollection<ItemCosting> ItemCostings { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
    }
}
