//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryMethod
    {
        public EntryMethod()
        {
            this.Orders = new HashSet<Order>();
            this.OrderCustoms = new HashSet<OrderCustom>();
            this.OrderOptions = new HashSet<OrderOption>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrderCustom> OrderCustoms { get; set; }
        public virtual ICollection<OrderOption> OrderOptions { get; set; }
    }
}
