//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureCustomerStore
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<Status> Status { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> Enterred { get; set; }
        public string Branch { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> MeasureId { get; set; }
    }
}
