//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNote
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int NoteTypeId { get; set; }
        public int SpokeWithId { get; set; }
        public string ContactName { get; set; }
        public System.DateTime DateTimeEntered { get; set; }
        public string NoteText { get; set; }
        public string EnteredByUserId { get; set; }
        public bool CustomerToCallBack { get; set; }
        public bool Scheduled { get; set; }
        public bool UnScheduled { get; set; }
        public Nullable<bool> ScheduledAM { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public bool Deleted { get; set; }
        public bool SentViaXML { get; set; }
        public Nullable<System.DateTime> DateTimeSent { get; set; }
    
        public virtual Employee EnteredBy { get; set; }
        public virtual NoteType NoteType { get; set; }
    }
}
