//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class POPhoto
    {
        public int ID { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> EnteredByUserID { get; set; }
        public int OrderID { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateTimeEntered { get; set; }
        public string Title { get; set; }
    }
}
