//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string UserId { get; set; }
        public int SlotTypeId { get; set; }
        public int MeasureId { get; set; }
    
        public virtual AspNetUser User { get; set; }
        public virtual Measure Measure { get; set; }
        public virtual SlotType SlotType { get; set; }
    }
}
