//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotType
    {
        public SlotType()
        {
            this.TechCapacities = new HashSet<TechCapacity>();
            this.Slots = new HashSet<Slot>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<TechCapacity> TechCapacities { get; set; }
        public virtual ICollection<Slot> Slots { get; set; }
    }
}
