//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreType
    {
        public StoreType()
        {
            this.ClientTypeReports = new HashSet<ClientTypeReport>();
            this.Programs = new HashSet<Program>();
        }
    
        public int Id { get; set; }
        public string ImageName { get; set; }
        public byte[] Logo { get; set; }
        public string QBClass { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ClientTypeReport> ClientTypeReports { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
    }
}
