//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandREng.MeasureDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWithBranch
    {
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string NickName { get; set; }
        public string StoreType { get; set; }
        public bool Active { get; set; }
        public string Number { get; set; }
        public Nullable<short> DistrictNumber { get; set; }
        public int Id { get; set; }
        public string BranchName { get; set; }
    }
}
