//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasuresMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreType
    {
        public StoreType()
        {
            this.Stores = new HashSet<Store>();
        }
    
        public int Id { get; set; }
        public string StoreTypeName { get; set; }
        public string ImageName { get; set; }
        public byte[] Logo { get; set; }
        public string QBClass { get; set; }
    
        public virtual ICollection<Store> Stores { get; set; }
    }
}
