//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasuresMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public int TypeID { get; set; }
        public string Number { get; set; }
        public string BillingAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string StorePhoneNumber { get; set; }
        public string DirectPhoneNumber { get; set; }
        public string Extension { get; set; }
        public string FaxNumber { get; set; }
        public string Notes { get; set; }
        public int BranchId { get; set; }
        public bool Active { get; set; }
        public string StoreNickName { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<short> DistrictNumber { get; set; }
        public bool IncludeInStatusReportAll { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual StoreType StoreType { get; set; }
    }
}
