//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasuresMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechCapacity
    {
        public int Id { get; set; }
        public int TechId { get; set; }
        public int SlotTypeId { get; set; }
        public byte Capacity { get; set; }
        public byte DayOfWeek { get; set; }
    
        public virtual SlotType SlotType { get; set; }
        public virtual Tech Tech { get; set; }
    }
}
